### ISSUE TITLE
GPU memory and speed improvements?

### ISSUE THREAD

**Issue by glennamarshall** [PARC/intricate-art-neural-transfer#1]
Hi
How long does the processing usually take?
On my GTX 1050 4gb it takes about 5 min to do 10 iterations. There's loads of out of memory errors.
I've been running other style transfer code on same computer and it zips through hundreds of iterations in a number of minutes, with just a few memory errors.
I have keras and tensorflow-gpu installed.

Is there anyway of improving performance?

**Comment by kramea** [comment]
Hi, I ran this on the GPU with 11 GB memory (depending on the style--I needed multiple GPUs). From what I understand, this particular style transfer needs more memory than the vanilla style transfer approach. 

One approach to improve performance is by reducing the image sizes, but that sacrifices the details of the pattern.

**Comment by glennamarshall** [comment]
Hey, thanks for your response. 
Looks like I'll just have to put up with long render times.. but at least I know it's to be expected. Thx.
